// Identity + organizations: generated by Better Auth (`pnpm --filter @repo/auth auth:generate`).
export * from "./auth";
// Learning: ours. Content metadata is owned by the content sync (S2); progress by @repo/learning.
export * from "./json";
export * from "./content";
export * from "./courses";
export * from "./assessments";
export * from "./progress";
// Shared systems (S5): moderation queue + audit log, notifications.
export * from "./moderation";
export * from "./notifications";
// Area 4 (S6): lesson feedback, course reviews, discussions.
export * from "./feedback";
// Certificates (S7).
export * from "./certificates";
// Badges, awards, and daily activity (S8).
export * from "./badges";
